# Generated by Django 3.2.7 on 2021-10-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211005_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dicription',
            new_name='discription',
        ),
    ]
